//! JSON format for requests and responses to the Silicon Flow API.

use serde::{Deserialize, Serialize};

/// The request body for the Silicon Flow API.
#[derive(Serialize)]
pub struct RequestBody<'a> {
    /// The model to use.
    pub model: &'a str,
    /// The input text.
    pub input: &'a [&'a str],
    /// The encoding format, either "float" or "base64".
    pub encoding_format: &'a str,
}

/// ResponseBody.data: The list of embeddings generated by the model.
#[derive(Deserialize)]
pub struct Data {
    /// Fixed string "embedding".
    #[serde(rename = "object")]
    _object: String,
    /// Base64-encoded embedding.
    pub embedding: String,
    /// Unused.
    #[serde(rename = "index")]
    _index: i32,
}

/// ResponseBody.usage: The usage information for the request.
#[derive(Deserialize)]
#[allow(dead_code, reason = "For deserialization only")]
#[allow(clippy::struct_field_names, reason = "Consistency with API response")]
pub struct Usage {
    /// The number of tokens used by the prompt.
    prompt_tokens: u32,
    /// The number of tokens used by the completion.
    completion_tokens: u32,
    /// The total number of tokens used by the request.
    total_tokens: u32,
}

/// The response body for the Silicon Flow API.
#[derive(Deserialize)]
pub struct ResponseBody {
    /// The name of the model used to generate the embedding.
    #[serde(rename = "model")]
    _model: String,
    /// The list of embeddings generated by the model.
    pub data: Vec<Data>,
    /// The usage information for the request.
    #[serde(rename = "usage")]
    _usage: Usage,
}
